DROP TABLE measurement;
DROP TABLE sensor;


CREATE TABLE sensor (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE measurement (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value NUMERIC(5,2) NOT NULL CHECK (value <= 100 AND value >= -100),
    raining BOOLEAN NOT NULL,
    registered_at timestamp NOT NULL,
    sensor_id int REFERENCES sensor(id) ON DELETE CASCADE
);


TRUNCATE TABLE sensor, measurement;

